#!/usr/bin/env python3
"""Persist OmaKeybinds overrides and validate the resulting Hyprland config."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path


BEGIN = "-- BEGIN io.github.oddlycrusty.omakeybinds managed overrides"
END = "-- END io.github.oddlycrusty.omakeybinds managed overrides"
CONFIG_HOME = Path(os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config")))
BINDINGS = CONFIG_HOME / "hypr/bindings.lua"
STATE = CONFIG_HOME / "omarchy/omakeybinds-overrides.json"


def normalize_key(value: str) -> str:
    tokens = [part.strip().upper() for part in re.split(r"\s*\+\s*", value.strip()) if part.strip()]
    modifiers = [name for name in ("SUPER", "CTRL", "ALT", "SHIFT") if name in tokens]
    keys = [name for name in tokens if name not in modifiers]
    return " + ".join(modifiers + keys)


def lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_state() -> dict[str, object]:
    try:
        data = json.loads(STATE.read_text(encoding="utf-8"))
        if isinstance(data, dict) and isinstance(data.get("overrides"), list):
            return data
    except (OSError, json.JSONDecodeError):
        pass
    return {"version": 1, "overrides": []}


def upsert_override(overrides: list[dict[str, str]], entry: dict[str, str]) -> list[dict[str, str]]:
    """Replace the same edit and any managed binding occupying its new key."""
    entry_id = entry["id"]
    new_key = normalize_key(entry["current_key"])
    kept = [
        item for item in overrides
        if item.get("id") != entry_id and normalize_key(item.get("current_key", "")) != new_key
    ]
    kept.append(entry)
    return kept


def managed_block(overrides: list[dict[str, str]]) -> str:
    lines = [BEGIN, "-- Generated by the OmaKeybinds plugin. Edit shortcuts through the GUI."]
    for item in overrides:
        original = normalize_key(item["original_key"])
        current = normalize_key(item["current_key"])
        lines.extend([
            "",
            f'-- {item["description"]}: {original} -> {"deleted" if item.get("kind") == "deleted" else current}',
            f"hl.unbind({lua_string(original)})",
        ])
        if current != original:
            lines.append(f"hl.unbind({lua_string(current)})")
        if item.get("kind") != "deleted":
            lines.append(f'o.bind({lua_string(current)}, {lua_string(item["description"])}, {item["action"]})')
    lines.extend([END, ""])
    return "\n".join(lines)


def replace_block(source: str, block: str) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)
    if pattern.search(source):
        return pattern.sub(block, source)
    return source.rstrip() + "\n\n" + block


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(content)
        os.replace(temporary, path)
    except Exception:
        Path(temporary).unlink(missing_ok=True)
        raise


def hyprctl(*arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["hyprctl", *arguments], capture_output=True, text=True, timeout=8, check=False)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--id", default="")
    parser.add_argument("--origin-key", required=True)
    parser.add_argument("--old-key", required=True)
    parser.add_argument("--new-key", required=True)
    parser.add_argument("--description", required=True)
    parser.add_argument("--action", required=True)
    parser.add_argument("--kind", choices=("default", "changed", "custom", "deleted"), required=True)
    parser.add_argument("--previous-kind", choices=("default", "changed", "custom"), default="")
    args = parser.parse_args()

    original = normalize_key(args.origin_key)
    old = normalize_key(args.old_key)
    new = normalize_key(args.new_key)
    if not original or not new or "\n" in new or '"' in new or len(new) > 120:
        print(json.dumps({"ok": False, "message": "That key combination is not valid."}))
        return 2
    if not args.action.strip() or "\0" in args.action:
        print(json.dumps({"ok": False, "message": "The original shortcut action could not be preserved."}))
        return 2

    state = load_state()
    overrides: list[dict[str, str]] = state["overrides"]  # type: ignore[assignment]
    override_id = args.id or hashlib.sha256(f"{original}\0{args.description}\0{args.action}".encode()).hexdigest()[:16]
    existing = next((item for item in overrides if item.get("id") == override_id), None)
    previous = existing.get("previous", f"{original} — {args.description}") if existing else f"{original} — {args.description}"
    entry = {
        "id": override_id,
        "original_key": original,
        "current_key": new,
        "description": args.description,
        "action": args.action,
        "kind": args.kind,
        "previous": previous,
    }
    if args.kind == "deleted":
        entry["previous_kind"] = args.previous_kind or (existing.get("kind", "changed") if existing else "changed")
    overrides = upsert_override(overrides, entry)
    state["overrides"] = overrides

    try:
        original_source = BINDINGS.read_text(encoding="utf-8")
    except OSError as error:
        print(json.dumps({"ok": False, "message": f"Could not read bindings.lua: {error}"}))
        return 1

    backup = BINDINGS.with_name(BINDINGS.name + ".bak.omakeybinds-" + datetime.now().strftime("%Y%m%d%H%M%S"))
    shutil.copy2(BINDINGS, backup)
    try:
        atomic_write(BINDINGS, replace_block(original_source, managed_block(overrides)))
        reload_result = hyprctl("reload")
        errors_result = hyprctl("configerrors")
        errors = errors_result.stdout.strip() or errors_result.stderr.strip()
        if reload_result.returncode != 0 or errors_result.returncode != 0 or errors:
            raise RuntimeError(errors or reload_result.stderr.strip() or "Hyprland rejected the binding")
        atomic_write(STATE, json.dumps(state, ensure_ascii=False, indent=2) + "\n")
    except Exception as error:
        shutil.copy2(backup, BINDINGS)
        try:
            hyprctl("reload")
        except Exception:
            pass
        print(json.dumps({"ok": False, "message": f"Change rolled back: {error}"}))
        return 1

    message = f"Deleted {old}" if args.kind == "deleted" else f"Changed {old} to {new}"
    print(json.dumps({"ok": True, "message": message, "backup": str(backup)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
