#!/usr/bin/env python3
"""Apply a fresh, explicitly selected shortcut through a private stdin request."""
from __future__ import annotations

import json
import re
import sys

import scan_shortcuts as scanner
from shortcut_model import binding_spec, display_key, lua_string, normalize_key
from shortcut_store import BEGIN, END, BINDINGS, STATE, digest, mutation_lock, replace_block, transaction


def upsert_override(overrides: list[dict], entry: dict) -> list[dict]:
    kept = []
    for item in overrides:
        if item["id"] == entry["id"]:
            continue
        if item["kind"] != "deleted" and item["current_key"] == entry["current_key"]:
            item = {**item, "kind": "deleted", "previous_kind": item["kind"]}
        kept.append(item)
    kept.append(entry)
    return kept


def managed_block(overrides: list[dict]) -> str:
    lines = [BEGIN, "-- Generated by OmaKeybinds. Edit shortcuts through the GUI."]
    # Unbind before adding ANY active binding: origins can be reused by another
    # override. Do not interpolate descriptions into executable Lua comments.
    keys = dict.fromkeys(normalize_key(item[field]) for item in overrides
                         for field in (("current_key",) if item.get("preserve_origin", False)
                                       else ("original_key", "current_key")))
    lines.extend(f"hl.unbind({lua_string(key)})" for key in keys)
    for item in overrides:
        if item["kind"] == "deleted":
            continue
        spec = binding_spec(item["action"], item["call"], item["options"])
        lines.append(f'{spec["call"]}({lua_string(normalize_key(item["current_key"]))}, '
                     f'{lua_string(item["description"])}, {spec["action"]}, {spec["options"]})')
    lines.extend([END, ""])
    return "\n".join(lines)


def read_request() -> dict:
    raw = sys.stdin.read(8193)
    if len(raw) > 8192:
        raise ValueError("The shortcut request is too large.")
    try:
        request = json.loads(raw)
        if not isinstance(request, dict) or set(request) != {"token", "snapshot", "new_key", "operation", "replace"}:
            raise ValueError()
        if any(not isinstance(request[k], str) for k in ("token", "snapshot", "new_key", "operation")):
            raise ValueError()
        if any(re.fullmatch(r"[a-f0-9]{64}", request[k]) is None for k in ("token", "snapshot")):
            raise ValueError()
        if request["operation"] not in ("edit", "delete", "restore") or type(request["replace"]) is not bool:
            raise ValueError()
        request["new_key"] = normalize_key(request["new_key"])
    except (ValueError, TypeError, RecursionError) as error:
        raise ValueError("Could not read the shortcut request.") from error
    return request


def apply_request(request: dict) -> dict:
    with mutation_lock(STATE):
        current, original, overrides = scanner.snapshot()
        if request["snapshot"] != current["snapshot"]:
            raise ValueError("Bindings changed since this view opened. Cancel, rescan, and try again.")
        selected = [item for item in current["items"] if item["token"] == request["token"]]
        if len(selected) != 1 or not selected[0]["editable"]:
            raise ValueError("This shortcut cannot be safely edited. Rescan and try again.")
        row = selected[0]
        operation = request["operation"]
        if row["disabled"] != (operation == "restore"):
            raise ValueError("The requested operation does not match this shortcut.")
        new_key = row["key"] if operation == "delete" else request["new_key"]
        conflicts = [item for item in current["items"] if not item["disabled"] and item["token"] != row["token"]
                     and (item["key"] == new_key or display_key(item["key"]) == display_key(new_key))]
        if operation == "restore" and conflicts:
            raise ValueError("The selected key is occupied. Choose another key to restore this shortcut; the current action will not be replaced.")
        if operation != "delete" and conflicts and not request["replace"]:
            raise ValueError("The selected key is occupied. Choose another key or explicitly confirm replacement.")
        if any(item["reason"] and "Submap" in item["reason"] for item in conflicts):
            raise ValueError("This key is used in a submap and cannot be safely replaced.")
        kind = "deleted" if operation == "delete" else row["restoreKind"] if operation == "restore" else "custom" if row["status"] == "custom" else "changed"
        entry = {
            "id": row["overrideId"] or digest(row["originKey"] + "\0" + row["description"] + "\0" + json.dumps(row["spec"], sort_keys=True))[:16],
            "original_key": row["originKey"], "current_key": new_key,
            "description": row["description"], "kind": kind,
            "previous": row["previous"] or row["displayKey"] + " — " + row["description"],
            **row["spec"],
            "created": row.get("created", False),
        }
        previous_entry = next((item for item in overrides if item["id"] == row["overrideId"]), {})
        if previous_entry.get("preserve_origin", False) or (operation == "restore" and not row["overrideId"]):
            # The source already removed this action. Starting management at
            # the restore destination avoids unbinding a new, unrelated owner
            # of its old key. Keep the old key in `previous` for display.
            entry["preserve_origin"] = True
        if operation == "delete":
            entry["previous_kind"] = row["status"]
        overrides = upsert_override(overrides, entry)
        block = managed_block(overrides)
        state = {"version": 2, "overrides": overrides, "block_digest": digest(block)}
        backups = transaction(BINDINGS, STATE, original, replace_block(original, block), state)
        return {"ok": True, "message": "Shortcut deleted." if operation == "delete" else "Shortcut saved.", **backups}


def main() -> int:
    try:
        result = apply_request(read_request())
    except UnicodeError:
        print(json.dumps({"ok": False, "message": "Configuration contains unsupported text encoding. No edit was completed."}))
        return 2
    except ValueError as error:
        print(json.dumps({"ok": False, "message": str(error)}))
        return 2
    except (OSError, RecursionError):
        print(json.dumps({"ok": False, "message": "Could not safely access shortcut configuration. Check file permissions and backups."}))
        return 1
    print(json.dumps(result, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
